### ISSUE TITLE
Get real position of selected value

### ISSUE THREAD

**Issue by JayasenaMS** [mirrajabi/search-dialog#6]
How to get selected item real potion. when search some item and select it then it return the selected chunk position not the real position.

**Comment by mirrajabi** [comment]
you mean you want to get the position of the item in initial array, not the position in result of search?

**Comment by JayasenaMS** [comment]
thnx for reply. yes, that's what I mean. I think it's better to return the position of the item in initial array.

**Comment by mirrajabi** [comment]
@JayasenaMS Thanks for the contribution,
It may suit your current purpose of usage but I don't know if it's really necessary to add that option to the project since it will have a bit of not-clean solution.
the simplest workaround for you will be setting an `id` on your searchable objects or overriding `equals()` in them and then check the result of the search dialog with your initial list.
If you can give me a better idea about this or you have any other solutions on this, I would be glad to know about it. Also any PRs are welcome ;)

**Comment by bhavikmehta5491** [comment]
This is actually much needed while using custom class arraylist

**Comment by raghavsatyadev** [comment]
> This is actually much needed while using custom class arraylist

@mirrajabi actually @bhavikmehta5491 and @JayasenaMS are in real world scenario right. I also thought that this library is returning position from initial array, was using it for some use case and then the bug came.

You should at least write somewhere in Readme and also in java doc of listener that this position is of chunk position.
